# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yuapi
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: travelmakers
# "service" is the name of this project. This will also be added to your AWS resource names.
service: v1

custom:
  config: ${file(./config.json)}

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  vpc:
    securityGroupIds:
      - sg-042109b54cc2715e7
      - sg-083f2bdf3e4af2a04
    subnetIds:
      - subnet-03d0b9e555af35e84
      - subnet-0c3cea5885053b83c
  deploymentBucket:
    name: ${self:custom.config.aws.bucketName}
  environment:
    DB_HOST: ${self:custom.config.db.DB_HOST}
    DB_USER: ${self:custom.config.db.DB_USER}
    DB_PASSWORD: ${self:custom.config.db.DB_PASSWORD}
    DB_NAME: ${self:custom.config.db.DB_NAME}
    DB_PORT: ${self:custom.config.db.DB_PORT}
    GOOGLE_API_KEY: ${self:custom.config.chat.google_key}
    PERPLEXITY_API_KEY: ${self:custom.config.chat.perplexity_key}
    OPENAI_API_KEY: ${self:custom.config.chat.openai_key}
    UNSPLASH_API_KEY: ${self:custom.config.image.unsplash_key}
    PIXABAY_API_KEY: ${self:custom.config.image.pixabay_key}

functions:
  hello:
    handler: helloHandler.hello
    events:
      - http:
          path: /v1/hello
          method: GET
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  listPosts:
    handler: postHandler.listPosts
    events:
      - http:
          path: /v1/post
          method: GET
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  createPost:
    handler: postHandler.createPost
    events:
      - http:
          path: /v1/post
          method: POST
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  readPost:
    handler: postHandler.readPost
    events:
      - http:
          path: /v1/post/{id}
          method: GET
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  updatePost:
    handler: postHandler.updatePost
    events:
      - http:
          path: /v1/post/{id}
          method: PUT
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  deletePost:
    handler: postHandler.deletePost
    events:
      - http:
          path: /v1/post/{id}
          method: DELETE
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  listComments:
    handler: commentHandler.listComments
    events:
      - http:
          path: /v1/comment/{pid}
          method: GET
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  createComment:
    handler: commentHandler.createComment
    events:
      - http:
          path: /v1/comment
          method: POST
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  readUser:
    handler: userHandler.readUser
    events:
      - http:
          path: /v1/user
          method: GET
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  updateUser:
    handler: userHandler.updateUser
    events:
      - http:
          path: /v1/user
          method: PUT
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  deleteUser:
    handler: userHandler.deleteUser
    events:
      - http:
          path: /v1/user
          method: DELETE
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  chat:
    handler: chatHandler.chat
    events:
      - http:
          path: /v1/chat
          method: POST
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  getImages:
    handler: imageHandler.getImages
    events:
      - http:
          path: /v1/images
          method: POST
  createCountry:
    handler: countryHandler.createCountry
    events:
      - http:
          path: /v1/country/dev
          method: POST
  readCountry:
    handler: countryHandler.readCountry
    events:
      - http:
          path: /v1/country
          method: POST
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF
  listCountry:
    handler: countryHandler.listCountry
    events:
      - http:
          path: /v1/country/list
          method: GET
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-2:975050034108:userpool/ap-northeast-2_XGR8vNEfF